import { Output, render } from "@alloy-js/core";
import { d } from "@alloy-js/core/testing";
import { describe, expect, it } from "vitest";
import * as thrift from "../index.js";
import { findFile } from "#test/utils.jsx";

describe("SourceFile", () => {
  it("renders header, includes, namespaces, and declarations in order", () => {
    const res = render(
      <Output namePolicy={thrift.defaultThriftNamePolicy}>
        <thrift.SourceFile
          path="test.thrift"
          headerComment="Generated by Alloy"
          includes={<thrift.Include path="shared.thrift" />}
          namespaces={<thrift.Namespace lang="js" value="example" />}
        >
          <thrift.Struct name="User">
            <thrift.Field id={1} type="string" name="name" />
          </thrift.Struct>
        </thrift.SourceFile>
      </Output>,
      { insertFinalNewLine: false },
    );

    const file = findFile(res, "test.thrift");
    expect(file.contents).toBe(d`
      /**
       * Generated by Alloy
       */

      include "shared.thrift"

      namespace js example

      struct User {
        1: string name;
      }
    `);
  });
});
