import { findFile } from "#test/utils.jsx";
import { Output, render } from "@alloy-js/core";
import { d } from "@alloy-js/core/testing";
import { describe, expect, it } from "vitest";
import {
  Field,
  Include,
  Namespace,
  SourceFile,
  Struct,
  defaultThriftNamePolicy,
  string,
} from "../index.js";

describe("SourceFile", () => {
  it("renders header, includes, namespaces, and declarations in order", () => {
    const res = render(
      <Output namePolicy={defaultThriftNamePolicy}>
        <SourceFile
          path="test.thrift"
          headerComment="Generated by Alloy"
          includes={<Include path="shared.thrift" />}
          namespaces={<Namespace lang="js" value="example" />}
        >
          <Struct name="User">
            <Field id={1} type={string} name="name" />
          </Struct>
        </SourceFile>
      </Output>,
      { insertFinalNewLine: false },
    );

    const file = findFile(res, "test.thrift");
    expect(file.contents).toBe(d`
      /**
       * Generated by Alloy
       */

      include "shared.thrift"

      namespace js example

      struct User {
        1: string name,
      }
    `);
  });
});
