/** @jsxImportSource @alloy-js/core */
import { code } from "@alloy-js/core";
import { d } from "@alloy-js/core/testing";
import { describe, it } from "vitest";
import * as gql from "../src/index.js";
import { assertFileContents, toGraphQLTextMultiple } from "./utils.js";

describe("SourceFile", () => {
  it("renders an empty source file", () => {
    const content = <gql.SourceFile path="schema.graphql" />;
    const res = toGraphQLTextMultiple([content]);

    assertFileContents(res, {
      "schema.graphql": d`
      
      `,
    });
  });

  it("renders a source file with types", () => {
    const content = (
      <gql.SourceFile path="schema.graphql">
        <gql.ObjectTypeDeclaration name="User">
          <gql.FieldDeclaration
            name="id"
            type={code`${gql.builtInScalars.ID}!`}
          />
          <gql.FieldDeclaration
            name="name"
            type={code`${gql.builtInScalars.String}!`}
          />
          <gql.FieldDeclaration name="email" type={gql.builtInScalars.String} />
        </gql.ObjectTypeDeclaration>
        <gql.ObjectTypeDeclaration name="Post">
          <gql.FieldDeclaration
            name="id"
            type={code`${gql.builtInScalars.ID}!`}
          />
          <gql.FieldDeclaration
            name="title"
            type={code`${gql.builtInScalars.String}!`}
          />
          <gql.FieldDeclaration
            name="content"
            type={gql.builtInScalars.String}
          />
        </gql.ObjectTypeDeclaration>
      </gql.SourceFile>
    );

    const res = toGraphQLTextMultiple([content], {});

    assertFileContents(res, {
      "schema.graphql": d`
        type User {
          id: ID!
          name: String!
          email: String
        }
        
        type Post {
          id: ID!
          title: String!
          content: String
        }
      `,
    });
  });

  it("renders a source file with header comment", () => {
    const content = (
      <gql.SourceFile
        path="schema.graphql"
        headerComment="Auto-generated schema"
      >
        <gql.ObjectTypeDeclaration name="User">
          <gql.FieldDeclaration
            name="id"
            type={code`${gql.builtInScalars.ID}!`}
          />
        </gql.ObjectTypeDeclaration>
      </gql.SourceFile>
    );

    const res = toGraphQLTextMultiple([content], {});

    assertFileContents(res, {
      "schema.graphql": d`
        # Auto-generated schema
        type User {
          id: ID!
        }
      `,
    });
  });

  it("renders a source file with documentation", () => {
    const content = (
      <gql.SourceFile
        path="schema.graphql"
        doc={`"""\nMain GraphQL schema for the application\n"""`}
      >
        <gql.ObjectTypeDeclaration name="User">
          <gql.FieldDeclaration
            name="id"
            type={code`${gql.builtInScalars.ID}!`}
          />
        </gql.ObjectTypeDeclaration>
      </gql.SourceFile>
    );

    const res = toGraphQLTextMultiple([content], {});

    assertFileContents(res, {
      "schema.graphql": d`
        """
        Main GraphQL schema for the application
        """
        type User {
          id: ID!
        }
      `,
    });
  });

  it("renders a source file with header and documentation", () => {
    const content = (
      <gql.SourceFile
        path="schema.graphql"
        headerComment="Generated by Alloy"
        doc={`"""\nUser management schema\n"""`}
      >
        <gql.ObjectTypeDeclaration name="User">
          <gql.FieldDeclaration
            name="id"
            type={code`${gql.builtInScalars.ID}!`}
          />
          <gql.FieldDeclaration
            name="name"
            type={code`${gql.builtInScalars.String}!`}
          />
        </gql.ObjectTypeDeclaration>
      </gql.SourceFile>
    );

    const res = toGraphQLTextMultiple([content], {});

    assertFileContents(res, {
      "schema.graphql": d`
        # Generated by Alloy
        """
        User management schema
        """
        type User {
          id: ID!
          name: String!
        }
      `,
    });
  });

  it("renders multiple source files in a schema", () => {
    const content = [
      <gql.SourceFile path="user.graphql">
        <gql.ObjectTypeDeclaration name="User">
          <gql.FieldDeclaration
            name="id"
            type={code`${gql.builtInScalars.ID}!`}
          />
          <gql.FieldDeclaration
            name="name"
            type={code`${gql.builtInScalars.String}!`}
          />
        </gql.ObjectTypeDeclaration>
      </gql.SourceFile>,
      <gql.SourceFile path="post.graphql">
        <gql.ObjectTypeDeclaration name="Post">
          <gql.FieldDeclaration
            name="id"
            type={code`${gql.builtInScalars.ID}!`}
          />
          <gql.FieldDeclaration
            name="title"
            type={code`${gql.builtInScalars.String}!`}
          />
        </gql.ObjectTypeDeclaration>
      </gql.SourceFile>,
    ];

    const res = toGraphQLTextMultiple(content);

    assertFileContents(res, {
      "user.graphql": d`
        type User {
          id: ID!
          name: String!
        }
      `,
      "post.graphql": d`
        type Post {
          id: ID!
          title: String!
        }
      `,
    });
  });

  it("renders a source file without content correctly", () => {
    const content = <gql.SourceFile path="empty.graphql" />;

    const res = toGraphQLTextMultiple([content]);

    assertFileContents(res, {
      "empty.graphql": d`
      
      `,
    });
  });
});
